@startuml


participant Portal
participant Sysman
participant "ESX-LCM"
participant "vsan-cluster-manager"
participant "vCenter"
participant "Host"

"vsan-cluster-manager"->vCenter: get_hosts()

note left
    It is discouraged to scale down/in the cluster
    but sometimes we have to do for various reason.
end note


group Scale down
    Portal->Sysman: remove_disks()
    Sysman->"ESX-LCM": request_disk_removal()
    "ESX-LCM"->"vsan-cluster-manager": scale_down_vsan_disks()
    "vsan-cluster-manager"->vCenter: get_hosts()
    "vsan-cluster-manager"->"vsan-cluster-manager": check_disk_sanity()

    loop for all hosts (in serial order)
        "vsan-cluster-manager"->vCenter: enter_host_maintenance()
        "vsan-cluster-manager"->vCenter: set_data_migration_policy()

        note left
          Assumption(s) / Choice points are:

          1) Server is hot-pluggable. So, removal of new disk does
             not need server reboot. If not so, we need to power
             recycle the host.
          2) All hosts are presented with same set of new disks to
             maintain homogenity of disk groups and nodes. It is
             technicallly possible to remove some disk from a select
             disk group of selected set of host but we are not going
             to support as it creates performance issue.
        end note

        "vsan-cluster-manager"->vCenter: remove_disk_claim()
        alt Expand existing disk group
            "vsan-cluster-manager"->vCenter: get_disk_group()
        else Remove disk group
            "vsan-cluster-manager"->vCenter: remomve_disk_group()
        end

        "vsan-cluster-manager"->vCenter: exit_host_maintenance()
        "vsan-cluster-manager"->vCenter: validate_capacity_shrink()
    end loop

    "vsan-cluster-manager"-> "vsan-cluster-manager": publish_scale_down_report()
    "vsan-cluster-manager"-->"ESX-LCM":
    "ESX-LCM"-->Sysman:
    Sysman->Sysman: remove_hosts_disks()
    Sysman->Portal: notify_result()
end

newpage

group Scale in
    Portal->Sysman: remove_node()
    Sysman->"ESX-LCM": request_node_removal()
    "ESX-LCM"->"vsan-cluster-manager": scale_down_vsan_nodes()
    "vsan-cluster-manager"->vCenter: get_hosts()

    group Perform scale in feasability check
        "vsan-cluster-manager"->"vsan-cluster-manager": check_node_shrink_feasability()
        note left
           As of now, we are not goign to support
           shrink of VSAN cluster from n-nodes to two nodes
           as it involves deployment of witness appliance
           etc. We will cover this post v1.
        end note
        "vsan-cluster-manager"->"vsan-cluster-manager": check_space_shrink_feasability()
    end

    alt if scale in criteria is passed
        loop for all hosts
            "vsan-cluster-manager"->vCenter: enter_host_maintenance()
            "vsan-cluster-manager"->vCenter: disable_vsan_network()
            "vsan-cluster-manager"->vCenter: resynchronize_vsan_cluster()
            "vsan-cluster-manager"->vCenter: exit_host_maintenance()
        end loop
        "vsan-cluster-manager"-> "vsan-cluster-manager": publish_scale_in_report()
    end

    "vsan-cluster-manager"-->"ESX-LCM":
    "ESX-LCM"-->Sysman:
    Sysman->Sysman: remove_nodes_from_platform()
    Sysman->Portal: notify_result()
end

@enduml