@startuml

class Cluster
class Addon

HelmChartAddon <|-- Addon
ConfigAddon <|-- Addon
Cluster "1" *-- "many" Addon : contains

Addon *- Attributes : has  >
Addon *- RealizedAttributes : has after realization  >

class Addon {
    String name
    String type
    String src
    String desiredVersion
    Target target
    Dependency[] dependency
    UserData userData
    Status status
}


class HelmChartAddon {
    String deployed_version
    String namespace
}

class ConfigAddon {
}


package "Utility classes" #DDDDDD {

    class UserDataDict {
    }

    class Dependency {
        String name
        String desiredVersionCondition
    }

    enum Status {
      Green
      Yellow
      Red
    }

    enum Target {
      master
      worker
      any
    }
}


@enduml