@startuml

actor nody

note over nody
    Nody represents one of the following:
        - Person calling API directly
        - Bot calling API
        - Another calling service system endpoint
        - Cli calling API

    It is just the we are focussed on accepting valid
    request and serving it.
end note

participant system
participant lcmEntryPoint
participant "theAPIEntryPoint"
participant "theRequest"
participant "theKubernetesManager"
participant "theHttpRequestReceiver"
participant "thePF9RequestReceiver"
participant thePersistentDatabaseEngine
participant theKubernetesBaremetalCluster


group
    system -> lcmEntryPoint: calls it
    lcmEntryPoint -> theKubernetesBeremetalManager: creates manager instance
    theKubernetesBeremetalManager -> thePersistentDataFactory: asks to create dbengine instance
    thePersistentDataFactory -> thePersistentDatabaseEngine: creates dbengine instance
    theKubernetesBeremetalManager -> thePersistentDatabaseEngine: Loads dbs (if exists)
    loop For every cluster
        theKubernetesBeremetalManager -> theKubernetesBaremetalCluster: creates
    end loop
end

group
    nody -> theAPIEntryPoint: receives a http request
    theAPIEntryPoint -> theAPIEntryPoint: calls theAPIEntryPoint.httpValidation()
    theAPIEntryPoint -> theRequest: creates theRequest
    theAPIEntryPoint -> theRequest: calls theRequest.execute()
    theRequest -> theKubernetesManager: calls theKubernetesManager.handle(request)
    theKubernetesManager -> theKubernetesManager: calls theKubernetesManager.theHttpRequestReceiver.do(request)
    alt in-house serveed request
        theHttpRequestReceiver -> theHttpRequestReceiver: process the request
        theHttpRequestReceiver --> theKubernetesManager:
        theKubernetesManager --> theAPIEntryPoint:
    else synchornous (blocking) request
        theHttpRequestReceiver -> theHttpRequestReceiver: process
        theHttpRequestReceiver -> thePF9RequestReceiver: routes to thePF9RequestReceiver
        thePF9RequestReceiver --> theHttpRequestReceiver:
        theHttpRequestReceiver --> theKubernetesManager:
        theKubernetesManager --> theAPIEntryPoint:
    else asynchornous request
        theHttpRequestReceiver -> theHttpRequestReceiver: process
        theHttpRequestReceiver -> theUSGIMessageBroker: drops a message
        thePF9RequestReceiver -> theUSGIMessageBroker: picks a message
        thePF9RequestReceiver -> thePF9RequestReceiver: process the mssage
        thePF9RequestReceiver -> theUSGIMessageBroker: drops a completion message
        theHttpRequestReceiver -> theHttpRequestReceiver: starts from where left
        theHttpRequestReceiver --> theKubernetesManager:
        theKubernetesManager --> theAPIEntryPoint:
    end
end



@enduml