
@startuml
actor Rollie

participant ConnectApp
participant "HPE OneSphere API"
participant K8sLCM
participant "PF9 API"

note over Rollie
    The below sequence talks about usage of ConnecApp to create cluster.

    Pre-requisite:

         1) ConnectApp has on-boarded and authorized servers
         2) ConnectApp has creatd pseudo zone representing kubernetes cluster.
         2) New NCS API is defined for cluster creation.

    Pros:

         1) Not dependent on PF9 UI
         2) Development effort is completely under the control of kuberentes team.

    Cons:

        1) New NCS API needs to be developed to create cluster
        2) The other lifecycle operation like delete, update and upgrade will mandate usage
           of ConnectApp which will be good user experience. ConnectApp is good for one
           time thing but not for repeated operations.

end note


Rollie -> ConnectApp: Request cluster creation
ConnectApp -> "HPE OneSphere API": Create cluster
"HPE OneSphere API" -> "HPE OneSphere API": Collect all the parameters needed for cluster creation
"HPE OneSphere API" -> K8sLCM: Request cluster creation
K8sLCM -> "PF9 API": Create cluster

note over Rollie
    to be continued...

    After this kuberentes LCM comes into picture and does set of activities
    like deploying marketplace agent, creating storage class etc which is
    same irrespective of mode Rollie choose to create cluster. See follow-up
    of completing post-cluster creation steps in separate sequence diagram.
end note

@enduml