@startuml

actor "HPE Operation Team"
participant "kubectl"
participant "Kubernetes"
participant "rds-restore"
participant "aws-rds"

"HPE Operation Team" --> kubectl: Start "rds-restore" pod to restore point-in-time
kubectl --> Kubernetes: Create pod
Kubernetes --> "rds-restore": Create the pod
activate "rds-restore"
"rds-restore" --> "rds-restore": Get AWS key(s)
"rds-restore" --> "aws-rds": Create NEW RDS instance
"rds-restore" --> "rds-restore": Determine list of DBs to be restored
loop for each database
    "rds-restore" --> "aws-rds": Dump database (from new instance) to local temp file
    "rds-restore" --> "aws-rds": Drop the database present in OLD instance
    "rds-restore" --> "aws-rds": Create the database in OLD instance (from dump file)
    "rds-restore" --> "rds-restore": Restart the service(s)
end loop

"rds-restore" --> "aws-rds": Delete the NEW RDS instance
deactivate "rds-restore"

@enduml