@startuml

actor "HPE Operation Team"
participant "kubectl"
participant "Kubernetes"
participant "rds-restore"
participant "aws-rds"


"HPE Operation Team" --> kubectl: Start "rds-restore" pod to create manual snapshot
kubectl --> Kubernetes: Create pod
Kubernetes --> "rds-restore": Create the pod
activate "rds-restore"
"rds-restore" --> "rds-restore": Get AWS keys
"rds-restore" --> "aws-rds": Create manual snapshot
deactivate "rds-restore"

@enduml