@startuml

actor Rollie

participant "HPE OneSphere"
participant "aws-snapshot-create"
participant "aws-ebs"


Rollie --> "HPE OneSphere": Deploys OneSphere
"HPE OneSphere" --> "aws-snapshot-create": Creates "aws-snapshot-create" pod

activate "aws-snapshot-create"
loop forever:
    "aws-snapshot-create" --> "aws-snapshot-create": Get AWS keys
    "aws-snapshot-create" --> "aws-ebs": Creates EBS volume snapshot
    "aws-snapshot-create" --> "aws-snapshot-create": Read backup policy
    "aws-snapshot-create" --> "aws-snapshot-create": Recycle old snapshot (if required)
     note left
        Based on backup policy, old snapshots
        are churned. The parameters which can
        be configred as of now are retention
        days and age of snapshot.
     end note
    "aws-snapshot-create" --> "aws-snapshot-create": Wait till next backup window occurs
end
deactivate "aws-snapshot-create"

@enduml