@startuml

actor "HPE Operation Team"
participant "kubectl"
participant "Kubernetes"
participant "ebs-buractl"
participant "aws-ebs"

group "Restore EBS volume for ms-monasca-influxdb service"
"HPE Operation Team" --> kubectl: Start "ebs-buractl" pod to restore volume


kubectl --> Kubernetes: Create pod
Kubernetes --> "ebs-buractl": Create the pod
activate "ebs-buractl"
"ebs-buractl" --> "ebs-buractl": Get AWS keys
"ebs-buractl" --> "ebs-buractl": Determine snpashot_id for restoration
note left
  Either user provides snapshot id.
  Or, system determines it by scanning already existing
  snapshot and picking latest one.
end note
"ebs-buractl" --> "aws-ebs": Re-create EBS volume from snapshot
"ebs-buractl" --> "Kubernetes": Restore ms-monasca-influxdb service to new volume
"ebs-buractl" --> "Kubernetes": Tag OLD volume (for traceability)
deactivate "ebs-buractl"
end group


group "List snapshot(s) of EBS volume consumed by service"
"HPE Operation Team" --> kubectl: Start "ebs-buractl" pod to enumerate snapshot(s)
kubectl --> Kubernetes: Create pod
Kubernetes --> "ebs-buractl": Create the pod
activate "ebs-buractl"
"ebs-buractl" --> "ebs-buractl": Get AWS keys
"ebs-buractl" --> "aws-ebs": Get list of snapshot(s)
"ebs-buractl" --> "ebs-buractl": Display snapshot(s) detail

end group
deactivate "ebs-buractl"

@enduml