@startuml

@startuml
skinparam backgroundColor #EEEBDC
skinparam handwritten true

skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DeepSkyBlue
	LifeLineBorderColor blue
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor DeepSkyBlue
	ParticipantBackgroundColor DodgerBlue
	ParticipantFontName Impact
	ParticipantFontSize 17
	ParticipantFontColor #A9DCDF

	ActorBackgroundColor aqua
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

participant CommServe
participant Client
participant MediaAgent
participant BackupStorage
participant ContentStore

CommServe -> Client: Initiates data protection
Client -> Client: Initiates scan phase to identify data to be protected
Client -> Client: Generates collect files to be protected
Client -> CommServe:
CommServe -> MediaAgent: Request to do backup
MediaAgent -> MediaAgent: Run data protection job
MediaAgent -> BackupStorage: Stores backup data
MediaAgent -> MediaAgent: Prepares index cache
MediaAgent -> ContentStore: Index are stored in library
MediaAgent --> CommServe

@enduml