@startuml


skinparam sequence {
    TitleFontSize 36
    TitleFontName Tahoma
    TitleFontColor DarkBlue


	ArrowColor DeepSkyBlue
	ActorBorderColor DeepSkyBlue
	LifeLineBorderColor blue
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor DeepSkyBlue
	ParticipantBackgroundColor DodgerBlue
	ParticipantFontName Impact
	ParticipantFontSize 20
	ParticipantFontColor #A9DCDF

	ActorBackgroundColor aqua
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}


header (C) Copyright 2019
footer author: Jyoti Ranjan

    |||
    |||
    |||

actor "GLHC Admin"
note over "GLHC Admin"
    The sequence diagram captures the workflow (or algorithm) 
    to bootstrap the GLCG. In this workflow, vCenter is 
    deployed in non-HA mode on independent ESXi host.

    The very minute details of installation of GUI application 
    is not too detailed to avoid cluttering the sequence diagram. 
    The scope of the diagram is to define the workflow for high 
    level design. For e.g. low level details of how to create
    RAID 10 lun using hpssacli or REDIS client or OneView in 
    case of Synergy is not covered.
end note

box "Seed machine" #LightGrey
    participant Client
end box

box "Management components" #LightBlue
    participant "Deployment Host"
    participant VCSA
    participant "Deployment Manager VM"
    participant "Deployment Manager"
end box

box "OmniStack components" #LightGreen
    participant "OmniStack Host"
end box

note over Client
    client is either a laptop or some machine to connect
    to ESXi host so that ESXi host can be configured and
    OS can be installed. The below workflow can be
    automated. The below mentioned workflow can be automated 
    using scripting languages.
end note

group Preparing deployment node
        |||
    "GLHC Admin" -> Client: Login
    "GLHC Admin" -> "Deployment Host": Power on the server
    "GLHC Admin" -> "Deployment Host": Create RAID lun
    "GLHC Admin" -> "Deployment Host": Install ESXi
        |||
end group


newpage

note over Client
    The below mentioned
    workflow can be automated using
    scripting languages.
end note

group Deploying management software(s)
        |||
    "GLHC Admin" -> Client: Login
    "GLHC Admin" -> Client: Download VCSA OVA
    "GLHC Admin" -> "Deployment Host": Create VCSA
    "GLHC Admin" -> "GLHC Admin": Note down VCSA url
        |||
    "GLHC Admin" -> "Deployment Host": Create "Deployment Manager VM"
    "GLHC Admin" -> "Deployment Manager VM": Run arbiter's msi installer
    "GLHC Admin" -> "Deployment Manager VM": Install Arbiter
        |||
    "GLHC Admin" -> "Deployment Manager VM": Download deployment manager's msi
    "GLHC Admin" -> "GLHC Admin": Prepare user input in yaml file
    "GLHC Admin" -> "Deployment Manager VM": Run jar file with user inputs
    "GLHC Admin" -> "Deployment Manager": Ensure installation is correct
        |||
    "GLHC Admin" -> "Deployment Manager VM": Download the vSphere web-plugin
    "GLHC Admin" -> "Deployment Manager VM": Install web-plugin
    "GLHC Admin" -> "Deployment Manager VM": Restart VMware "vsphere-ui" service
        |||
    "GLHC Admin" -> "GLHC Admin": Verify deployment environment
        |||
end

newpage


note over "GLHC Admin"
    The below mentioned workflow can be automated using
    scripting languages.
end note


group Creating OmniStack cluster
        |||
    loop for every GLCG host
        "GLHC Admin" -> "OmniStack Host": Power on
        "GLHC Admin" -> "OmniStack Host": Assign static IP address
        "GLHC Admin" -> "GLHC Admin": Note down IP
    end
        |||
    "GLHC Admin" -> "Deployment Manager VM": Login (if you haven't)
    "GLHC Admin" -> "Deployment Manager VM": Open "Deployment Manager"
    activate "Deployment Manager"
        "GLHC Admin" -> "Deployment Manager": Create SimpliVity federation
        "GLHC Admin" -> "Deployment Manager": Feed Arbiter IP
        "GLHC Admin" -> "Deployment Manager": Scan OmniStack hosts
        "GLHC Admin" -> "Deployment Manager": Configure federation
        "GLHC Admin" -> "Deployment Manager": Configure network
        "GLHC Admin" -> "Deployment Manager": Configure NTP
        "GLHC Admin" -> "Deployment Manager": Run tests
    deactivate "Deployment Manager"
        |||
end group

newpage

note over "Deployment Manager VM"
    The below mentioned workflow can be automated using
    scripting languages.
end note

group Preparing OmniStack cluster for consumption
        |||
   "GLHC Admin" -> "Deployment Manager VM": Open vCenter
   "GLHC Admin" -> "Deployment Manager VM": Create datastore
   "GLHC Admin" -> "Deployment Manager VM": Create backup policy (if desired)
        |||
end group

@enduml