@startuml

actor operator
participant "hellfire-ism"
participant "update_system.yml"
participant oneview

operator->"hellfire-ism": update oneview

note left
    The workflow talks about upgrade of oneview version.
end note

"hellfire-ism"->"update_system.yml": Run it

"update_system.yml"->"update_system.yml": load config variables
"update_system.yml"->"update_system.yml": call get_infrastructure_environment()
"update_system.yml"->"update_system.yml": call get_infrastructure_credential_by_uri()
"update_system.yml"->"update_system.yml": call make_update_params()
"update_system.yml"->oneview: login
"update_system.yml"->"update_system.yml": save oneview auth token
"update_system.yml"->oneview: update oneview
"update_system.yml"->oneview: run firmware update playbook

@enduml