@startuml
participant "ESX-LCM"
participant "vsan-cluster-manager"
participant "vCenter"
participant "Host"

"ESX-LCM"->"vsan-cluster-manager": setup()

note left
In below discussion, the reference of cluster is for vsan
cluster unless stated specifically.  The sequence diagram
is based on certain assumptions as mentioned below.

Host preparation::

1) Disks are presented to host as per storage model.
2) VSAN network is created with all hosts connected to it.
3) Vmkernl adopter is enabled for all hosts.

Cluster configuration::

1) Hybrid cluster is supported only as of now.
2) All nodes are uniform and hence contains same
   disk and compute specification.
3) Only default storage policy is created.

end note



"vsan-cluster-manager"->"vsan-cluster-manager": collect_setup_attributes()

note right
Cluster setup and configuration needs access of cluster
and host API along with choices asked by user. The following
attributes needs to be collected:

1) username and password
2) certificate
3) license
4) vmware storage model
5) type = {hybrid, flash}

The specific configuration related to following is not covered
as of now:

fault domain support,
the enablement of performance services and
multi-cast support if more than one cluster share same subnet
compression and deduplication

end note

newpage

"vsan-cluster-manager"->vCenter: get_cluster_instance(user, password, cert)
"vsan-cluster-manager"->vCenter: apply_vsan_license(license)
"vsan-cluster-manager"->vCenter: get_hosts()

loop for all hosts
    "vsan-cluster-manager"->Host: get_host_details()
    "vsan-cluster-manager"->"vsan-cluster-manager": validate_network_settings()
    "vsan-cluster-manager"->"vsan-cluster-manager": validate_disk_settings()
    "vsan-cluster-manager"->"vsan-cluster-manager": validate_memory_settings()
end loop

"vsan-cluster-manager"->"vsan-cluster-manager": publish_compliance_report()
loop for all ESXi hosts:
    loop for all vsan disks of a given host
        "vsan-cluster-manager"->Host: update_disk_partition()
    end loop
end loop

newpage

"vsan-cluster-manager"->vCenter: reconfigure_cluster()
"vsan-cluster-manager"->"vsan-cluster-manager": wait_for_completion()
"vsan-cluster-manager"->"vsan-cluster-manager": prepare_cluster_diskmap()
loop for all disk in diskmap
    "vsan-cluster-manager"->vCenter: claim_disks()
    note left
        Results in creation of disk group.
    end note
end loop
"vsan-cluster-manager"->"vsan-cluster-manager": wait_for_completion()

"vsan-cluster-manager"->vCenter: query_diskmap()
"vsan-cluster-manager"->vCenter: match_cluster_diskmap()

@enduml